### ISSUE TITLE
Go to Definition is not working

### ISSUE THREAD

**Issue by insiderq** [msaraiva/atom-elixir#29] opened 2016-04-26 11:38 UTC
When i hit with Alt at module User that is defined in another file inside `lib/` nothing happens.
Console logs the following `elixir-goto-definition-provider.coffee:64 Can't find "User"` 
Same behaviour for all modules, even standart ones.
`[atom-elixir] Initializing alchemist-server for environment "dev" (Elixir version 1.1.1)` is shown at the beginning and Find Documentation function is working as well as autocompletion. 
Go to definition just can't find modules.

Mac OS El Capitan

**Comment by VladShcherbin** [comment] 2016-05-21 14:44
Same issue.

**Comment by msaraiva** [comment] 2016-06-27 20:43
There's a new version v0.2.1. Please, update and check if the problem is gone. Also remember to restart Atom after update or hit `CTRL+ALT-CMD-L` on mac.

Thanks for reporting the issue.

**Comment by insiderq** [comment] 2016-06-27 21:02
All mine modules are found now, Thanks! Standard's modules like Enum are not, but i think that is the way it supposed to be. Am i wrong?

**Comment by msaraiva** [comment] 2016-06-27 21:23
@insiderq it should definitely work for any standard module as long as the sources are available in your environment. How did you install Elixir?

**Comment by insiderq** [comment] 2016-06-27 21:43
I installed Elixir via `brew`, it is definetely added to `PATH` in `zsh`, and probably in `bash` too (since when i do `bash` and then `iex` everything is working). When i `cd` into my project folder and use `iex -S mix run` everything is working too (obviously).

**Comment by insiderq** [comment] 2016-06-27 21:52
I thought a little more and understand that probably brew installes only binaries. Given that that's remaining to be unclear what means "available in environment". Which environment variable should reflec Elixir's source and in what way exactly?

**Comment by msaraiva** [comment] 2016-06-27 22:15
If brew installs only binaries then "Goto definition" cannot work for those modules. A workaround would be to pull the sources and copy them to the same folder defined in the binary file. Run `Enum.module_info(:compile)[:source]` on `iex` to check where the sources were located originally, when elixir was compiled. The better solution would be to have another brew package to install the sources.

**Comment by insiderq** [comment] 2016-06-27 22:22
I think that's no way=( `/private/tmp/elixir20160221-36085-19qilli/elixir-1.2.3/lib/elixir/lib/enum.ex`

**Comment by insiderq** [comment] 2016-06-27 22:25
Is there a possibility to have an environment variable corresponding to the elixir source location configured via package settings for example and for every find module attempt add a subsequent search in a source directory.

Of course described option wuold require coding. I just mean, is it on the plan?

**Comment by msaraiva** [comment] 2016-06-27 22:42
Closing this in favor of https://github.com/msaraiva/atom-elixir/issues/35

**Closed by msaraiva** 2016-06-27 22:42 UTC
