### ISSUE TITLE
Go to definition not work

### ISSUE THREAD

**Issue by quannguyen89** [msaraiva/atom-elixir#23] opened 2016-04-08 06:55 UTC
Hi!

I tried to use `option+up` or `option+click` but I couldn't go to definition. Could you resolve this issue?

Thanks!

**Comment by mbramson** [comment] 2016-04-10 23:58
Confirming I am having this problem as well on both Ubuntu 14.04 and Windows 7. When I hover, the word is underlined, but clicking it does nothing.

**Comment by msaraiva** [comment] 2016-04-11 22:48
Hi,

I will certainly need more information. Please, try this:

- Restart Atom
- Open your Elixir/Mix project (in case it's not opened yet)
- Hit `ALT+CMD+i` to open the console (ALT+CTRL+i on windows/linux, i guess). You should see something like:
```
[atom-elixir] Initializing alchemist-server for environment "dev" (Elixir version 1.2.0)
```
- If you don't see that, you should see some error message from the alchemist-server. If that's the case, please let me know what the message looks like.
- In case the server is has successfully started, make sure your project compiles. Most of the features of atom-elixir only works if you have the related `.beam` files in the `_build` folder.

Thanks.

**Comment by tv4-infrastruktur** [comment] 2016-04-13 11:37
We got the following when trying to navigate to `Evergent.authenticate` when having a `alias Account.Evergent`.

```
[atom-elixir] Initializing alchemist-server for environment "dev" (Elixir version 1.2.4)

server-process.coffee:149 [Server] DEFL { "Evergent,authenticate", "/Users/fyranadm/Code/account/web/controllers/authentication_controller.ex", "/var/folders/15/rt5286951s3c_pxdp98kwbwm0000gn/T/bqu4gssvc", 12 }
```

**Comment by msaraiva** [comment] 2016-04-19 01:13
If the server has started and your files were successfully compiled, there's no reason not to work. Is it possible for any of you to push to github a minimal project simulating the problem?

Thanks.

**Comment by chrisjowen** [comment] 2016-06-22 01:21
+1 on OSX

**Comment by msaraiva** [comment] 2016-06-27 20:45
There's a new version v0.2.1. Please, update and check if the problem is gone. Also remember to restart Atom after update or hit `CTRL+ALT-CMD-L` on mac.

Thanks for reporting the issue.

**Comment by msaraiva** [comment] 2016-06-27 22:44
Closing this in favor of https://github.com/msaraiva/atom-elixir/issues/35

**Closed by msaraiva** 2016-06-27 22:44 UTC
